import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import editors from '../data/editors'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion";


export default function Home() {
  const [currId, setCurrId] = useState(0)
  const Titlevariants = {
  hidden: { opacity: 0, x: -500, y: 0 },
  enter: { opacity: 1, x: 0, y: 0 },
  exit: { opacity: 0, x: 0, y: -100 },
};
  return (
    <div className={styles.container}>
      <Head>
        <title>Editores de video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      <motion.div
        variants={Titlevariants}
        initial="hidden"
        animate="enter"
        exit="exit"
        transition={{ type: "linear" }}
      >
        <h1 className={styles.title}>Editores de video</h1>
      </motion.div>
        <div className={styles.grid}>
          {
            editors.map((item, index) => 
            <>
            
              <Link href={{ pathname:"/editor", query:{editorId: item.id}}}>
              <a className={styles.card}>
                <h2>{item.editorName} &rarr;</h2>
                <img src={item.imageUri} alt="lol" layout='fill'/>
              </a>
              </Link>
            </>
            )
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
